<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '"{attribute}" must be a valid JSON' => 'uzb_"{attribute}" должен содержать валидный JSON',
    'Active' => 'uzb_Активно',
    'API access token' => 'uzb_Токен доступа к API',
    'Article ID' => 'uzb_ID Статьи',
    'Article View' => 'uzb_Шаблон статьи',
    'Author' => 'uzb_Автор',
    'Base URL' => 'uzb_Базовый URL',
    'Base Url' => 'uzb_Базовый Url',
    'Body' => 'uzb_Текст',
    'Caption' => 'uzb_Текст',
    'Carousel ID' => 'uzb_ID карусели',
    'Category' => 'uzb_Категория',
    'Comment' => 'uzb_Комментарий',
    'Component' => 'uzb_Компонент',
    'Config' => 'uzb_Настройки',
    'Created At' => 'uzb_Создано',
    'Created at' => 'uzb_Создано',
    'Deleted' => 'uzb_Удалено',
    'Down to maintenance.' => 'uzb_Закрыто на обслуживание.',
    'E-mail' => 'uzb_E-mail',
    'Email' => 'uzb_Email',
    'Expire At' => 'uzb_Истекает',
    'File Type' => 'uzb_Тип файла',
    'Firstname' => 'uzb_Имя',
    'Gender' => 'uzb_Пол',
    'ID' => 'uzb_ID',
    'Image' => 'uzb_Изображение',
    'Key' => 'uzb_Ключ',
    'Last login' => 'uzb_Последний вход',
    'Lastname' => 'uzb_Фамилия',
    'Locale' => 'uzb_Локаль',
    'Middlename' => 'uzb_Отчество',
    'Name' => 'uzb_Имя',
    'Not Active' => 'uzb_Неактивно',
    'Order' => 'uzb_Порядок',
    'Page View' => 'uzb_Шаблон страницы',
    'Parent Category' => 'uzb_Родительская категория',
    'Password' => 'uzb_Пароль',
    'Path' => 'uzb_Путь',
    'Picture' => 'uzb_Аватар',
    'Published' => 'uzb_Опубликовано',
    'Published At' => 'uzb_Дата публикации',
    'Roles' => 'uzb_Роли',
    'Size' => 'uzb_Размер',
    'Slug' => 'uzb_ЧПУ',
    'Status' => 'uzb_Статус',
    'Thumbnail' => 'uzb_Эскиз изображения',
    'Title' => 'uzb_Название',
    'Token' => 'uzb_Токен',
    'Type' => 'uzb_Тип',
    'Updated At' => 'uzb_Обновлено',
    'Updated at' => 'uzb_Последнее обновление',
    'Updater' => 'uzb_Обновивший',
    'Upload Ip' => 'uzb_IP',
    'Url' => 'uzb_Url',
    'User ID' => 'uzb_ID пользователя',
    'Username' => 'uzb_Имя пользователя',
    'Value' => 'uzb_Значение',
];
