<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'uzb_О нас',
    'Activation email' => 'uzb_Письмо активации',
    'Account Settings' => 'uzb_Настройки аккаунта',
    'Articles' => 'uzb_Статьи',
    'Attachments' => 'uzb_Приложения',
    'Backend' => 'uzb_Панель управления',
    'Body' => 'uzb_Сообщение',
    'Check your email for further instructions.' => 'uzb_Проверьте ваш e-mail.',
    'Confirm Password' => 'uzb_Подтвердите пароль',
    'Contact' => 'uzb_Контакты',
    'E-mail' => 'uzb_E-mail',
    'Email' => 'uzb_Email',
    'Error while oauth process.' => 'uzb_Ошибка в процессе OAuth авторизации.',
    'Female' => 'uzb_Женский',
    'Home' => 'uzb_Главная',
    'If you forgot your password you can reset it <a href="{link}">here</a>' => 'uzb_Если вы забыли пароль, вы можете сбросить его <a href="{link}">здесь</a>',
    'Incorrect username or password.' => 'uzb_Неправильный логин или пароль.',
    'Language' => 'uzb_Язык',
    'Log in with' => 'uzb_Войти с помощью',
    'Login' => 'uzb_Вход',
    'Logout' => 'uzb_Выход',
    'Male' => 'uzb_Мужской',
    'Name' => 'uzb_Имя',
    'Need an account? Sign up.' => 'uzb_Нужен аккаунт? Зарегистрируйтесь',
    'New password was saved.' => 'uzb_Новый пароль был сохранён',
    'Page not found' => 'uzb_Страница не найдена',
    'Password' => 'uzb_Пароль',
    'Password reset for {name}' => 'uzb_Сброс пароля для {name}',
    'Profile settings' => 'uzb_Настройки профиля',
    'Remember Me' => 'uzb_Запомнить меня',
    'Request password reset' => 'uzb_Запрос сброса пароля',
    'Reset password' => 'uzb_Сброс пароля',
    'Settings' => 'uzb_Настройки фис',
    'Sign up with' => 'uzb_Создать аккаунт с помощью',
    'Signup' => 'uzb_Регистрация',
    'Sorry, we are unable to reset password for email provided.' => 'uzb_Извините, мы не можем сбросить пароль для этого e-mail.',
    'Subject' => 'uzb_Тема',
    'Submit' => 'uzb_Отправить',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'uzb_Спасибо. Мы свяжемся с Вами в ближайшее время.',
    'There was an error sending email.' => 'uzb_Ошибка при отправке сообщения.',
    'This email address has already been taken.' => 'uzb_Этот e-mail уже занят.',
    'This email has already been taken.' => 'uzb_Этот e-mail уже занят.',
    'This username has already been taken.' => 'uzb_Это имя пользователя уже занято.',
    'Update' => 'uzb_Редактировать',
    'User Settings' => 'uzb_Настройки пользователя',
    'Username' => 'uzb_Имя пользователя',
    'Username or email' => 'uzb_Имя пользователя или e-mail',
    'Verification Code' => 'uzb_Проверочный код',
    'We already have a user with email {email}' => 'uzb_Пользователь с e-mail {email} уже зарегистрирован.',
    'Welcome to {app-name}. Email with your login information was sent to your email.' => 'uzb_Добро пожаловать в {app-name}. E-mail с информацией о пользователе был отправлен на вашу почту.',
    'Your account has been successfully activated.' => 'uzb_Ваш аккаунт был успешно активирован. ',
    'Your account has been successfully created. Check your email for further instructions.' => 'uzb_Ваш аккаунт был успешно создан. Проверьте ваш e-mail.',
    'Your account has been successfully saved' => 'uzb_Ваш аккаунт был успешно сохранён',
    'Your activation link: {url}' => 'uzb_Ссылка активации: {url}',
    '{app-name} | Your login information' => 'uzb_{app-name} | Информация о пользователе',
];
